version: '3.6'

services:

  mongo:
    image: mongo:4.4.25
    restart: always
    volumes:
      - 'mongovolume-db:/data/db'
      - 'mongovolume-config:/data/configdb'

  elfin:
    image: elfinconnect:production
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 8443:8443
    environment:
      - NGINX_HOST=[YOUR_DOMAIN]
      - NODE_ENV=production
      - WEBPORT=3000
      - DATABASE=database:27017
      - DATABASE_COLLECTION=elfinconnect
      - GATEWAY_SERVER_IP=localhost
      - GATEWAY_SERVER_PORT=3001
      - GATEWAY_SERVER_TIMEOUT=30000
    links:
      - "mongo:database"

#  dynamic-dns:
#    image: dns-update
#    restart: always
#    environment:
#      - DYNAMIC_DNS_URL=[PUBLIC_DNS_PROVIDER_ADDRESS]

volumes:
  mongovolume-db:
    external: true
    name: mongo-data-production

  mongovolume-config:
    external: true
    name: mongo-config-production
